### ISSUE TITLE
getVisibleSatellites return empty array

### ISSUE THREAD

**Issue by samuelcardillo** [davidcalhoun/tle.js#12]
Hi, 

I am trying to use TLE.js and everything was going quite well until I tried to use getVisibleSatellites. I am using `spacetrack` npm module to retrieve the most recent TLEs of certain satellites (all the SkySat ones) which then put in an array which therefore becomes of an array of arrays : 

 ```json
[
[
  '0 SKYSAT C12',
  '1 43797U 18099AR  20029.52879878 +.00000391 +00000-0 +19261-4 0  9990',
  '2 43797 097.3805 103.0646 0003500 182.3187 177.8034 15.23559221063758'
]
[
  '0 SKYSAT C13',
  '1 43802U 18099AW  20029.48568984 +.00000420 +00000-0 +20441-4 0  9990',
  '2 43802 097.3802 103.5570 0006225 141.4162 218.7521 15.23646196063618'
]
]
```

Then I try fill the function with the correct parameters : 

```js
tle.getVisibleSatellites({
      observerLat: 37.614740,
      observerLng: 34.533634,
      tles: arrayOfArrays,
      timestampMS: startingDate
    });
```

And the result is an empty array. I tried iterating through a one week timestamp every 30 seconds but still the exact same and I can't find a proper solution. 

Am I doing something wrong ?

**Comment by davidcalhoun** [comment]
Hey, small world!  I used to work at Skybox, the company that launched those satellites :)

I think something is wrong on your side unfortunately - I'd log your `arrayOfArrays` to make sure it's formatted correctly.

If you check with https://www.n2yo.com/passes/?s=43797# you can see the timestamps of the next passes over you.  I was able to get a result with the following, using your same TLE and lat/lng:

```js
const tles = [
	[
		"0 SKYSAT C12",
		"1 43797U 18099AR  20029.52879878 +.00000391 +00000-0 +19261-4 0  9990",
		"2 43797 097.3805 103.0646 0003500 182.3187 177.8034 15.23559221063758"
	]
];

const allVisible = getVisibleSatellites({
	observerLat: 37.61474,
	observerLng: 34.533634,
	observerHeight: 0,
	tles,
	elevationThreshold: 0,
	timestampMS: 1580372100000
});

->
[
  {
    tleArr: [
      '0 SKYSAT C12',
      '1 43797U 18099AR  20029.52879878 +.00000391 +00000-0 +19261-4 0  9990',
      '2 43797 097.3805 103.0646 0003500 182.3187 177.8034 15.23559221063758'
    ],
    info: {
      lng: 35.80973400964123,
      lat: 32.6680981485973,
      elevation: 37.90872252964439,
      azimuth: 167.66790488533985,
      range: 765.6241128634699,
      height: 497.43671713422464,
      velocity: 7.620085604067198
    }
  }
]
```

**Comment by samuelcardillo** [comment]
Small world indeed ! We are using SkySat for specific tasking so thanks not only for the code but also contributing in launching this very useful constellation 😁

By passing the variable `arrayOfArrays` as a const named `tles` (just like in your example) it then work like a charm. I am just now facing a problem with the way I try to predict passages over a week and I am guessing it comes from my timestamp but I am not sure. 

```js
function getPasses() {
  const tles = exports.registeredTLE;
  let startingDate = new Date();
  startingDate = startingDate.setHours(startingDate.getHours(), 00, 00, 00);
  let endDate = startingDate + 86400000;
  let satInfo = [];

  for (var addedSeconds = 0; addedSeconds < 86400000; addedSeconds = addedSeconds + 300000) {
    let currentDate = startingDate + addedSeconds;

    satInfo.push(tle.getVisibleSatellites({
      observerLat: 34.533634,
      observerLng: 37.614740,
      tles,
      timestampMS: currentDate
    }));

    if (currentDate === (endDate - 300000)) {
      console.log("Finished - " + satInfo.length + " predictions acquired");

      console.log(JSON.stringify(satInfo))
    }
  }
}
```

Depending on the starting date (if I round the hour up - like in this example - or not), the number of MS between each predictions and the windows of prediction (one day in this example), the results are completely different. In one I get results only from C12, in other I get results from C1, C2 and C3... 

Is there a proper and more logical way to do that ?

**Comment by samuelcardillo** [comment]
Hi, I am still stuck with this, I literally can't find a solution :/ Is there anyone with more knowledge that could help me ? Please ?

**Comment by davidcalhoun** [comment]
Sorry for the delay.  I believe I found the culprit in some bad caching logic on my side.  Checking in a fix shortly.

**Comment by davidcalhoun** [comment]
Feel free to reopen or comment!
