### ISSUE TITLE
re-add support for commonJS?

### ISSUE THREAD

**Issue by timotejroiko** [davidcalhoun/tle.js#13]
Hello,

i have tried updating tle.js from 2.x.x to 3.x.x in a project of mine running on node v12.14.1 LTS, and it seems i cannot use anymore.

require() = cannot require ES modules
import() = error not supported (or self is not defined in tlejs.umd.js line 4 with experimental-modules enabled)
import x from = cannot import from outside of ES module

Do i have to rewrite my entire project into ES module syntax?

EDIT: i ended up renaming tlejs.umd.js to tlejs.umd.cjs in both the dist folder and in package.json to be able to use it

**Comment by davidcalhoun** [comment]
Doh, sounds like I introduced a regression with the latest release.  Sorry about that.  I'm away from my laptop for a few days, but will take a look when I get back.  Thanks for the heads up!

**Comment by davidcalhoun** [comment]
@timotejroiko I added a CommonJS build target in `3.1.0`, so you should be able to use functions with this format now:

```js
const { getLatLngObj }  = require("tle.js/dist/tlejs.cjs");
```

**Comment by timotejroiko** [comment]
thank you very much :)
