### ISSUE TITLE
Caching based on Satellite name causes incorrect return values

### ISSUE THREAD

**Issue by craigjmidwinter** [davidcalhoun/tle.js#14]
In some cases there are satellites listings with different TLEs but that have the same name (for instance, the ISS debris is all reported with a name of `ISS DEB`).

If you use the 3 element syntax in the library which includes the satellite name, you will get incorrect results once the entity has been parsed once. For example:

```
const issDebris1 = [
  'ISS DEB',
  '1 44303U 98067QA  20168.11979959  .00002872  00000-0  50277-4 0  9995',
  '2 44303  51.6421 345.5785 0004933 328.2807  31.7886 15.54325834 59558',
];

const issDebris2 = [
  'ISS DEB',                 
  '1 44304U 98067QB  20168.07956297  .00014700  00000-0  17368-3 0  9997',
  '2 44304  51.6395 337.0565 0003893 303.8223  56.2400 15.61553656 59676'
];

getCatalogNumber(issDebris1); // 44303
getCatalogNumber(issDebris2); // 44303 (should be 44304)
```
Not a huge deal, since an easy enough work around is to just omit the name element.

**Comment by davidcalhoun** [comment]
Great catch, thank you for the steps to reproduce!  Will get out a fix soon.
