### ISSUE TITLE
typescript types :(

### ISSUE THREAD

**Issue by lamo2k123** [davidcalhoun/tle.js#15]
there are no types for typescript

**Comment by davidcalhoun** [comment]
There's definitely more folks using TS these days.  I'm not against having some types exported if they could be added without converting all the code over to TS (I'm unsure of how that would work).  Pull requests are definitely welcomed!

**Comment by davidcalhoun** [comment]
@lamo2k123 I've just added TypeScript support in `tle.js@4.2.0`.  Please check it out and let me know how it goes!
