### ISSUE TITLE
How to get range sat?

### ISSUE THREAD

**Issue by behnamnazarpak** [davidcalhoun/tle.js#17]
Hello and thank you for this cool library ☺️
I need to get rangeSat on every position change of satellite , so how can i get this?

**Comment by thkruz** [comment]
You need to iterate. I recommend using a for loop where the variable (i for example) is the number of seconds added to Date.now.

So you call calculate rangeSat at Date.now + 0, push the result to an array, loop to Date.now + 1 and do it again, etc.

This should be limited to a set amount of time. You said "all" which could be thousands of years before the satellite reenters the atmosphere.

**Comment by davidcalhoun** [comment]
Thank you @thkruz!  A loop with 1 second intervals sounds like the way to go for sure - try that out and see if it works.

One note - if using a mercator projection, you may need higher resolutions (< 1000 ms) at the poles due to map distortion.

**Comment by davidcalhoun** [comment]
Closing this out.  @behnamnazarpak feel free to reopen and/or comment.
