### ISSUE TITLE
Problems with unusual/extreme orbits

### ISSUE THREAD

**Issue by davidcalhoun** [davidcalhoun/tle.js#21]
Examples: POLAR BEAR [?], MOLNIYA 1-32

Also, would be good to refine handling of geosync satellites

**Comment by thkruz** [comment]
@davidcalhoun any additional details on this? I assume you are talking about the sgp4 functions, but happy to help if you can clarify what the issue was.

**Comment by davidcalhoun** [comment]
Thanks, I'm going to close this one out.  I think the original issue was that some unusual orbits sometimes return SGP4 errors but it should be easier to debug now that [errors are thrown](https://github.com/davidcalhoun/tle.js/blob/master/src/sgp4.js#L25) in these cases.
