### ISSUE TITLE
In cesuim, I want draw the orbit of the satellite, through tle.js

### ISSUE THREAD

**Issue by xingzhenlu** [davidcalhoun/tle.js#22]
In cesuim, I want draw the orbit of the satellite, through tlejs.
cesuim can use Cesium.Cartesian3(x,y,z) or Cesium.Cartesian3.fromDegrees(longitude, latitude, height).
I can not get (x,y,z)!
I use the function getLatLngObj(tle, timestamp),can not get "height"!
How do I get the "height"？Help Me!

**Comment by davidcalhoun** [comment]
Please see the docs for [getSatelliteInfo](https://github.com/davidcalhoun/tle.js#getsatelliteinfotle-optionaltimestamp-observerlat-observerlng-observerelevation), which returns height.

**Comment by xingzhenlu** [comment]
```script
/**
     * 根据tle和一组时间，计算卫星轨道
     * @param {string} tleStr 两行轨道数据，星历
     * @param {[]} times 时间的数组，数组元素是Date()
     * @returns {[]} 卫星轨道数据
     */
    Calc2(tleStr, times) {
        //const tleStr2 = `ISS (ZARYA)
        //1 25544U 98067A   17206.18396726  .00001961  00000-0  36771-4 0  9993
        //2 25544  51.6400 208.9163 0006317  69.9862  25.2906 15.54225995 67660`;
        let rs = [];
        for (var i = 0; i < times.length; i++) {
            const time = times[i];
            const optionalTimestampMS = time.getTime();
            let latLonObj = getLatLngObj(tleStr, optionalTimestampMS);
            let satInfo = getSatelliteInfo(
                tleStr,                 // Satellite TLE string or array.
                optionalTimestampMS,    // Timestamp (ms)
                latLonObj.lat,          // Observer latitude (degrees)
                latLonObj.lng,          // Observer longitude (degrees)
                0                       // Observer elevation (km)
            )
            rs.push({
                timeStamp: optionalTimestampMS,
                latitude: latLonObj.lat,
                longitude: latLonObj.lng,
                height: satInfo.height,//km
            })
        }
        return rs;

        //输出解释
        //{
        //    // satellite compass heading from observer in degrees (0 = north, 180 = south)
        //    azimuth: 294.5780478624994,
        //    // satellite elevation from observer in degrees (90 is directly overhead)
        //    elevation: 81.63903620330046,
        //    // km distance from observer to spacecraft
        //    range: 406.60211015810074,
        //    // spacecraft altitude in km
        //    height: 402.9082788620108,
        //    // spacecraft latitude in degrees
        //    lat: 34.45112876592785,
        //    // spacecraft longitude in degrees
        //    lng: -117.46176597710809,
        //    // spacecraft velocity (relative to observer) in km/s
        //    velocity: 7.675627442183371
        //}
    }
```
1、Your method does work, but does it affect performance by the way?
2、What's the difference between "range" and "height"? Are they different because the earth is an irregular ellipsoid?
3、In satellite.js,There is such a piece of code：
```script
 var positionAndVelocity = satellite.propagate(satrec, new Date());
```
It got a different result!Is it the result of gravitational perturbation?

**Comment by thkruz** [comment]
1. All calculations take time and will affect performance. But without doing them, you won't have the information needed. These are very efficient calculations.

2. Range is the distance between the observer and the object. Height is the distance between the object and the surface of the earth. When the object is directly overhead they are the same. 

3. Position is an x, y, z location in 3D space where 0, 0, 0 is the center of the earth. Velocity is a vector in that 3D space. These are both different than range, azimuth, elevation, and height calculations.

**Comment by xingzhenlu** [comment]
Thank you！ @thkruz @davidcalhoun
