### ISSUE TITLE
TypeScript types error: getEpochTimestamp() needs an argument, but doesn't accept one

### ISSUE THREAD

**Issue by theheckwr** [davidcalhoun/tle.js#25]
As seen below, the example shows the function taking an argument, but the TypeScript definition doesn't reflect that, which leads to a syntax error.
![grafik](https://user-images.githubusercontent.com/22587394/147396541-8a457303-7cb0-4ca4-a777-636bf83123db.png)

Syntax error:
![grafik](https://user-images.githubusercontent.com/22587394/147396622-34ddbd05-8994-4eb8-9804-5d4631cce9f7.png)

**Comment by davidcalhoun** [comment]
Thanks for the heads up!  This is now fixed in `4.3.1`.  Let me know if you find any other discrepancies - will also accept PRs.

**Comment by theheckwr** [comment]
Thanks for the quick reaction!
Okay, maybe next time I do a PR, I wasn't really sure I got the issue right.

**Comment by davidcalhoun** [comment]
No worries, whichever way works best for you.  Thank you again for the heads up!
