### ISSUE TITLE
Nest.js: Unable to import

### ISSUE THREAD

**Issue by theheckwr** [davidcalhoun/tle.js#27]
# Problem
Compilation fails when using tle.js with nest.js:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <redacted>/node_modules/tle.js/dist/tlejs.umd.js
require() of ES modules is not supported.
require() of <redacted>/node_modules/tle.js/dist/tlejs.umd.js from <redacted>/dist/services/spacecraft-data.service.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename tlejs.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <redacted>/node_modules/tle.js/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (<redacted>/src/services/spacecraft-data.service.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

# Workaround
Remove the `"type": "module",` line from the package.json

# Solution
*I don't know (yet). Maybe remove the line and everything would be fine? Or does that cause other problems?*

**Comment by davidcalhoun** [comment]
Thanks for the heads up, it looks like Next.js doesn't yet support ES Modules: https://github.com/nestjs/nest/pull/8736

The good news is that it's a quick fix for you - you can tell it to explicitly use the CommonJS dist:

```ts
const { getLatLngObj } = require("tle.js/dist/tlejs.cjs");
```

I verified this works by running their [TypeScript starter project](https://docs.nestjs.com/) and outputting some test code in their `app.service.ts` Hello World:

```ts
import { Injectable } from '@nestjs/common';
const { getLatLngObj } = require("tle.js/dist/tlejs.cjs");

const tle = `ISS (ZARYA)
1 25544U 98067A   17206.18396726  .00001961  00000-0  36771-4 0  9993
2 25544  51.6400 208.9163 0006317  69.9862  25.2906 15.54225995 67660`;

@Injectable()
export class AppService {
  getHello(): string {
    return `Hello World! ${JSON.stringify(getLatLngObj(tle))}`;
  }
}
```

**Comment by theheckwr** [comment]
Okay, thanks for the info and the "temporary" solution.
That's way better than my workaround. I've implemented it and it works so far.
Let's hope they'll implement it soon.

**Comment by davidcalhoun** [comment]
Great, glad that works!  I am seeing a similar error with a simple Node project so I think I may be packaging it a bit wrong, looking into this!

**Comment by davidcalhoun** [comment]
In tle.js `4.5.0` I've added [Node.js conditional exports](https://nodejs.org/api/packages.html#conditional-exports) support which seems to resolve the issue!

**Comment by theheckwr** [comment]
Unfortunately when I try to import it with TypeScript into my Nest.js project, that fails with a "Can't find module declaration or corresponding type declaration" (Even my IDE (vs-code) shows this...).
Maybe this is a problem again with Nest.js but it looks like a TypeScript thing to me. Maybe something with my TypeScript config?

**Comment by davidcalhoun** [comment]
Oof, thanks for the heads up, I'm not sure what's going on there.  As a workaround you'll have to lock it down to the prior version for now (`npm i tle.js@4.4.0`).  Sorry for the hassle!

**Comment by theheckwr** [comment]
Yes, that's what I did already.
But thanks anyways for the help so far.

**Comment by davidcalhoun** [comment]
When you have a chance, please try again with `4.5.3`, I believe I finally tracked down the issue!  Thanks again.

**Comment by theheckwr** [comment]
Okay, I tested it.
It works so far. No errors and the functions I'm using are executing normally, as far as I see. Even with Nest.js.
Thanks very much!

**Comment by davidcalhoun** [comment]
Woo!  Good stuff, thanks for your patience!

**Comment by thkruz** [comment]
@davidcalhoun can you close this?

**Comment by davidcalhoun** [comment]
Sounds good, closing this out!
