### ISSUE TITLE
Babelify transform script fails if path contains spaces

### ISSUE THREAD

**Issue by vorg** [davidcalhoun/tle.js#3]
![screen shot 2017-11-14 at 15 15 31 copy](https://user-images.githubusercontent.com/171001/32787585-c999474a-c94e-11e7-862f-3dbe91fd93e9.jpg)

**Comment by davidcalhoun** [comment]
Thanks for reporting this issue!  Will look into just bundling the dist with the package, should remove errors like this and speed up installs.  :)

**Comment by davidcalhoun** [comment]
Thanks again!  For simplicity and faster build times, the library's dist is now bundled :)  Should be fixed in `1.0.20`
