### ISSUE TITLE
Accuracy of AZ and EL

### ISSUE THREAD

**Issue by jbreed** [davidcalhoun/tle.js#6]
Currently looking at some output and it appears the look angles are several degrees off other sources. Curious if there is something else that I need to handle, or if I'm doing something incorrectly.

```
var tleArr = [
    line1,
    line2
]

var observer = {
    lat: myLat,
    lng: myLng,
    height: myHeight
}
var timestampMS = (new Date).getTime()
var satInfo = tle.getSatelliteInfo(
    tleArr,
    timestampMS,
    observer.lat,
    observer.lng,
    observer.height
)

console.log("AZ: "+satInfo.azimuth)
console.log("EL:"+satInfo.elevation)
```

the satellite initially reviewing shows 156.2(true)&152.4*(magn)* on other sources (within a few decimals between sources) whereas I am getting 158*. I am also seeing the elevation on other sources show ~51.2* with this code returning 46.5*.

The inclination is 4.7707. Unsure if I need to take any other aspects into account to align things up properly.

**Comment by jbreed** [comment]
Update,

I believe it surely has something to do with the inclination because running it against several other satellites I get almost exact results. My guess is to simply add the inclination to the EL, but not understanding how to correct the AZ

**Comment by davidcalhoun** [comment]
Thanks for the report!  I believe this is an issue with an older version of `satellite.js` I'm using.  Until I can update it here, you may just want to use it directly: https://github.com/shashwatak/satellite-js

**Comment by jbreed** [comment]
Thanks David. I tried using it directly, but having issues getting back any valid information. Maybe you can quickly catch what I'm doing wrong. 

https://github.com/shashwatak/satellite-js/issues/41

**Comment by davidcalhoun** [comment]
Closing this out - feel free to reopen if it's still an issue!
